import { Dimensions, Platform, StyleSheet } from "react-native"

const { width } = Dimensions.get("window")

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mapContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  map: {
    flex: 1,
  },
  menuButton: {
    position: "absolute",
    top: Platform.OS === "ios" ? 50 : 30,
    left: 20,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    padding: 12,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 6,
  },
  closeButton: {
    position: "absolute",
    top: Platform.OS === "ios" ? 50 : 30,
    right: 15,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    padding: 10,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
    zIndex: 11,
  },
  mapOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.15)",
    zIndex: 5,
  },
  profileContainer: {
    alignItems: "center",
    marginTop: 25,
    marginBottom: 30,
    paddingBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  avatarContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    overflow: "hidden",
    marginBottom: 15,
    borderWidth: 3,
    borderColor: "#FF69B4",
    shadowColor: "#FF1493",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  avatar: {
    width: "100%",
    height: "100%",
  },
  username: {
    fontSize: 19,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  userRole: {
    fontSize: 15,
    color: "#777",
    fontWeight: "500",
  },
  menuSection: {
    marginBottom: 20,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginVertical: 5,
  },
  menuText: {
    fontSize: 16,
    marginLeft: 15,
    color: "#333",
    fontWeight: "500",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: -10,
    paddingVertical: 14,
    backgroundColor: "#FF1493",
    borderRadius: 12,
    paddingHorizontal: 20,
    justifyContent: "center",
    shadowColor: "#FF1493",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  logoutText: {
    fontSize: 16,
    color: "#fff",
    marginLeft: 10,
    fontWeight: "600",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.98)", // Increased opacity for better visibility
    paddingHorizontal: 20,
    paddingTop: 25, // Increased padding
    paddingBottom: Platform.OS === "ios" ? 50 : 40, // Increased bottom padding
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 }, // Stronger shadow
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 15, // Higher elevation for Android
    zIndex: 5,
    minHeight: 140, // Ensure minimum height for collapsed state
  },
  // NUEVOS ESTILOS PARA EL FORMULARIO DESPLEGABLE
  collapseButton: {
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  formScrollView: {
    flex: 1,
  },
  // New styles for input with icons
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    paddingHorizontal: 15,
    height: 50,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    width: "100%",
    height: 50,
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    fontSize: 15,
  },
  inputWithIcon: {
    flex: 1,
    marginBottom: 0,
    backgroundColor: "transparent",
    shadowColor: "transparent",
    elevation: 0,
    borderWidth: 0,
  },
  button: {
    width: "100%",
    backgroundColor: "#FF1493",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 20,
    shadowColor: "#FF1493",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  // Improved avatar menu styling
  avatarMenuContainer: {
    position: "absolute",
    top: Platform.OS === "ios" ? 50 : 30,
    right: 20,
    zIndex: 10,
  },
  avatarSmall: {
    width: 50,
    height: 50,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#B33F8D",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 8,
  },
  avatarButtonContainer: {
    shadowColor: "#B33F8D",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  menuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9,
  },
  dropdownMenu: {
    position: "absolute",
    top: 60,
    right: 0,
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    width: 200,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 11,
  },
  dropdownHeader: {
    backgroundColor: "rgba(255, 105, 180, 0.1)",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  dropdownHeaderText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FF1493",
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  dropdownText: {
    fontSize: 16,
    marginLeft: 12,
    color: "#333",
    fontWeight: "500",
  },
  logoutItem: {
    backgroundColor: "rgba(255, 20, 147, 0.08)",
  },
  logoutItemText: {
    color: "#FF1493",
    fontWeight: "600",
  },
  menuIconContainer: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  // Para las sugerencias de direcciones
  searchContainer: {
    width: "100%",
    position: "relative",
  },
  searchingIndicator: {
    position: "absolute",
    right: 15,
    top: 15,
  },
  suggestionsContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    maxHeight: 200,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  suggestionsList: {
    width: "100%",
    maxHeight: 200,
  },
  suggestionItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  suggestionText: {
    fontSize: 15,
    color: "#333",
    marginBottom: 2,
  },
  suggestionSubtext: {
    fontSize: 13,
    color: "#888",
  },
  noSuggestionsContainer: {
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  noSuggestionsText: {
    color: "#888",
    marginLeft: 10,
  },
  // Para la selección de vehículos
  vehicleSelectionContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 15,
  },
  vehicleOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  vehicleOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f9f9f9",
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#eee",
  },
  selectedVehicleOption: {
    backgroundColor: "#FF1493",
    borderColor: "#FF1493",
  },
  vehicleText: {
    marginTop: 5,
    fontSize: 14,
    fontWeight: "500",
    color: "#333",
  },
  selectedVehicleText: {
    color: "#fff",
  },
  // Para la estimación de precios
  priceEstimateContainer: {
    backgroundColor: "#f9f9f9",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#eee",
  },
  priceEstimateLabel: {
    fontSize: 14,
    color: "#555",
    marginBottom: 5,
  },
  priceEstimateValue: {
    fontSize: 24,
    fontWeight: "700",
    color: "#FF1493",
    marginBottom: 5,
  },
  distanceText: {
    fontSize: 14,
    color: "#777",
  },
  // NUEVOS ESTILOS AGREGADOS
  priceContainer: {
    width: "100%",
    position: "relative",
  },
  priceEstimateText: {
    fontSize: 14,
    color: "#FF1493",
    fontWeight: "600",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 5,
    backgroundColor: "#fff0f5",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ffb6c1",
  },
  // Botón desactivado
  buttonDisabled: {
    backgroundColor: "#ffb6c1",
    shadowOpacity: 0.1,
  },
  // Botón de prueba
  testButton: {
    position: "absolute",
    bottom: 150,
    left: "10%",
    right: "10%",
    backgroundColor: "#FF1493",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#FF1493",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 4,
  },
  testButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  // Modal de conductora
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  driverModalContainer: {
    width: "80%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  driverProfilePicture: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: "#FF1493",
  },
  driverName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#333",
    marginBottom: 10,
  },
  driverVehicle: {
    fontSize: 16,
    color: "#555",
    marginBottom: 5,
  },
  driverLicensePlate: {
    fontSize: 16,
    color: "#FF1493",
    fontWeight: "600",
    marginBottom: 20,
  },
  closeModalButton: {
    backgroundColor: "#FF1493",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  closeModalButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },

  // Overlay para el formulario expandido
formOverlay: {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: "rgba(0,0,0,0.3)",
  zIndex: 4,
},
})

export default styles