import { Dimensions, Platform, StyleSheet } from "react-native";
import { rf, rs, rw } from "../../utils/responsive";

const { width, height } = Dimensions.get("window")

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  // ─── HEADER ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 45 : 25,
    paddingBottom: 12,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(42, 14, 63, 0.15)",
  },
  profileIconSmall: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#F3EEF8",
    borderWidth: 2,
    borderColor: "#5A189A",
    alignItems: "center",
    justifyContent: "center",
  },
  headerInfo: {
    flex: 1,
    marginLeft: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#3B0F5C",
  },
  headerSubtitle: {
    fontSize: 15,
    color: "#5A189A",
    marginTop: 1,
  },
  statusIndicator: {
    alignItems: "center",
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },

  // ─── LISTA ─────────────────────────────────────────────────────────────────
  requestsList: {
    flex: 1,
    paddingHorizontal: 12,
    marginTop: 8,
  },
  listContainer: {
    paddingBottom: 16,
  },

  // ─── TARJETA DE SOLICITUD ──────────────────────────────────────────────────
  deliveryRequestCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderLeftWidth: 3,
    borderLeftColor: "#5A189A",
  },

  // Header de la tarjeta
  requestHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#F3EEF8",
  },
  clientInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    flexWrap: "wrap",
    gap: 6,
  },
  clientIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F3EEF8",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  clientName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#3B0F5C",
  },

  // Badge frágil
  fragileBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F59E0B",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    gap: 4,
  },
  fragileBadgeSmallText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
  },

  // Badge negociación
  negotiationBadge: {
    backgroundColor: "#5A189A",
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 8,
  },
  negotiationBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
  },

  // ─── UBICACIONES ───────────────────────────────────────────────────────────
  locationsContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#F3EEF8",
  },
  locationsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  locationCompact: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  locationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#5A189A",
    marginRight: 8,
    marginTop: 4,
  },
  destinationDot: {
    backgroundColor: "#3B0F5C",
  },
  locationInfo: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 10,
    color: "#5A189A",
    fontWeight: "700",
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  locationLabel2: {
    fontSize: 10,
    color: "#5A189A",
    fontWeight: "700",
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  locationAddress: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 2,
    flexWrap: "wrap",
  },
  locationNeighborhood: {
    fontSize: 12,
    color: "#5A189A",
    fontWeight: "500",
    marginTop: 1,
  },
  locationArrow: {
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  referencePoint: {
    fontSize: 11,
    color: "#5A189A",
    marginTop: 2,
    flexWrap: "wrap",
  },
  referenceLabel: {
    color: "#5A189A",
    fontWeight: "600",
  },

  // ─── PRECIO Y NEGOCIACIÓN ──────────────────────────────────────────────────
  priceMainContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: "#F3EEF8",
  },
  priceLeftSection: {
    flex: 1,
  },
  priceAmount: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#5A189A",
  },
  priceNegotiationContainer: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  originalPrice: {
    fontSize: 14,
    color: "#B0A0C0",
    textDecorationLine: "line-through",
  },
  counterOfferPrice: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#5A189A",
  },
  negotiateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#5A189A",
    backgroundColor: "#F3EEF8",
  },
  negotiateButtonText: {
    fontSize: 13,
    color: "#5A189A",
    fontWeight: "600",
  },
  priceEditContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  priceInput: {
    borderWidth: 1.5,
    borderColor: "#5A189A",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 14,
    width: 90,
    textAlign: "center",
    backgroundColor: "#F3EEF8",
    color: "#3B0F5C",
  },
  submitPriceButton: {
    backgroundColor: "#5A189A",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelPriceButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#5A189A",
    borderRadius: 8,
  },
  waitingResponse: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3EEF8",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#5A189A",
    gap: 4,
  },
  waitingResponseText: {
    fontSize: 12,
    color: "#5A189A",
    fontWeight: "500",
  },

  // ─── BOTONES ACCIÓN ────────────────────────────────────────────────────────
  actionButtons: {
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  rejectButton: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#5A189A",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  rejectButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#5A189A",
  },
  acceptButton: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: "#5A189A",
    alignItems: "center",
  },
  acceptButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
  acceptButtonDisabled: {
    backgroundColor: "#C9B8D9",
  },
  acceptButtonTextDisabled: {
    color: "#9B8BAF",
  },

  // ─── PEDIDO ACEPTADO ───────────────────────────────────────────────────────
  acceptedDeliveryContainer: {
    flex: 1,
    paddingVertical: rs(8),
    paddingHorizontal: rs(4),
  },
  acceptedDeliveryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: rs(16),
    paddingHorizontal: rs(4),
    flexWrap: "wrap",
    gap: rs(8),
  },
  acceptedDeliveryTitle: {
    fontSize: rf(20),
    fontWeight: "bold",
    color: "#3B0F5C",
    flexShrink: 1,
  },
  deliveryStatusBadge: {
    backgroundColor: "#5A189A",
    paddingHorizontal: rs(10),
    paddingVertical: rs(5),
    borderRadius: rs(20),
    flexShrink: 1,
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  deliveryStatusText: {
    color: "#fff",
    fontSize: rf(11),
    fontWeight: "600",
  },

  // Tarjeta cliente aceptado
  clientDetailCard: {
    backgroundColor: "#fff",
    borderRadius: rs(16),
    padding: rs(14),
    marginBottom: rs(10),
    marginHorizontal: rs(2),
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  clientIconLarge: {
    width: rw(56),
    height: rw(56),
    borderRadius: rw(28),
    backgroundColor: "#F3EEF8",
    alignItems: "center",
    justifyContent: "center",
    marginRight: rs(12),
    borderWidth: 2,
    borderColor: "#5A189A",
  },
  clientDetailInfo: {
    flex: 1,
  },
  clientNameLarge: {
    fontSize: rf(18),
    fontWeight: "bold",
    color: "#3B0F5C",
    marginBottom: rs(6),
  },
  fragileBadgeLarge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F59E0B",
    paddingVertical: rs(3),
    paddingHorizontal: rs(10),
    borderRadius: rs(10),
    gap: rs(4),
    alignSelf: "flex-start",
    marginBottom: rs(8),
  },
  fragileBadgeText: {
    color: "#fff",
    fontSize: rf(11),
    fontWeight: "bold",
  },
  contactButtonsLarge: {
    flexDirection: "row",
    gap: rs(8),
    flexWrap: "wrap",
  },
  whatsappButtonLarge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#25D366",
    paddingHorizontal: rs(12),
    paddingVertical: rs(8),
    borderRadius: rs(20),
    gap: rs(5),
    flex: 1,
  },
  callButtonLarge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#5A189A",
    paddingHorizontal: rs(12),
    paddingVertical: rs(8),
    borderRadius: rs(20),
    gap: rs(5),
    flex: 1,
  },
  contactButtonText: {
    color: "#fff",
    fontSize: rf(12),
    fontWeight: "600",
  },

  // Ruta detallada
  routeDetailCard: {
    backgroundColor: "#fff",
    borderRadius: rs(16),
    padding: rs(14),
    marginBottom: rs(10),
    marginHorizontal: rs(2),
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  routePoint: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  routePointDot: {
    width: rs(12),
    height: rs(12),
    borderRadius: rs(6),
    backgroundColor: "#5A189A",
    marginRight: rs(14),
    marginTop: rs(4),
  },
  destinationDotLarge: {
    backgroundColor: "#3B0F5C",
  },
  routePointInfo: {
    flex: 1,
  },
  routePointLabel: {
    fontSize: rf(10),
    color: "#5A189A",
    fontWeight: "700",
    marginBottom: rs(3),
    letterSpacing: 0.5,
  },
  routePointAddress: {
    fontSize: rf(15),
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: rs(3),
  },
  routePointNeighborhood: {
    fontSize: rf(12),
    color: "#5A189A",
  },
  routePointReference: {
    fontSize: rf(11),
    color: "#5A189A",
    marginTop: rs(4),
    flexWrap: "wrap",
  },
  routeLine: {
    width: 2,
    height: rs(24),
    backgroundColor: "#C9A7EB",
    marginLeft: rs(5),
    marginVertical: rs(5),
  },

  // Precio acordado
  priceDetailCard: {
    backgroundColor: "#5A189A",
    borderRadius: rs(16),
    paddingVertical: rs(16),
    paddingHorizontal: rs(20),
    marginBottom: rs(14),
    alignItems: "center",
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
    width: "70%",
    alignSelf: "center",
  },
  priceDetailLabel: {
    fontSize: rf(10),
    color: "rgba(255,255,255,0.85)",
    marginBottom: rs(4),
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  priceDetailAmount: {
    fontSize: rf(28),
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 0.5,
  },

  // Botones de acción del pedido aceptado
  deliveryActionButtons: {
    flexDirection: "row",
    gap: rs(10),
    marginTop: rs(4),
    paddingHorizontal: rs(2),
  },
  cancelDeliveryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#E74C3C",
    paddingVertical: rs(14),
    borderRadius: rs(12),
    gap: rs(6),
  },
  cancelDeliveryButtonText: {
    color: "#E74C3C",
    fontSize: rf(14),
    fontWeight: "600",
  },
  completeDeliveryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5A189A",
    paddingVertical: rs(14),
    borderRadius: rs(12),
    gap: rs(6),
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  completeDeliveryButtonText: {
    color: "#fff",
    fontSize: rf(14),
    fontWeight: "600",
  },

  // ─── REFERENCIA Y NOTAS (pedido aceptado) ──────────────────────────────────
  referencePill: {
    marginLeft: rs(26),
    marginTop: rs(6),
    marginBottom: rs(6),
    backgroundColor: "#F3EEF8",
    borderRadius: rs(8),
    padding: rs(8),
    borderLeftWidth: 3,
    borderLeftColor: "#5A189A",
  },
  referencePillText: {
    fontSize: rf(11),
    color: "#3B0F5C",
    flexWrap: "wrap",
  },
  referencePillLabel: {
    fontWeight: "600",
    color: "#5A189A",
  },

  // ─── ESTADOS VACÍOS ────────────────────────────────────────────────────────
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: rs(32),
  },
  emptyStateText: {
    fontSize: rf(16),
    fontWeight: "600",
    color: "#5A189A",
    marginTop: rs(12),
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: rf(13),
    color: "#9B8BAF",
    marginTop: rs(6),
    textAlign: "center",
  },
  inactiveState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: rs(32),
  },
  inactiveStateText: {
    fontSize: rf(16),
    fontWeight: "600",
    color: "#5A189A",
    marginTop: rs(12),
    textAlign: "center",
  },
  inactiveStateSubtext: {
    fontSize: rf(13),
    color: "#9B8BAF",
    marginTop: rs(6),
    textAlign: "center",
  },

  // ─── FOOTER ────────────────────────────────────────────────────────────────
  footer: {
    paddingHorizontal: rs(16),
    paddingVertical: rs(16),
    paddingBottom: Platform.OS === "ios" ? rs(30) : rs(20),
  },
  footerContent: {
    gap: rs(12),
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    paddingHorizontal: rs(14),
    paddingVertical: rs(12),
    borderRadius: rs(12),
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  statusText: {
    fontSize: rf(15),
    fontWeight: "600",
    color: "#3B0F5C",
  },
  statusSwitch: {
    transform: [{ scaleX: 1.0 }, { scaleY: 1.0 }],
  },
  updateLocationButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: rs(6),
    backgroundColor: "#fff",
    paddingHorizontal: rs(14),
    paddingVertical: rs(12),
    borderRadius: rs(12),
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  updateLocationText: {
    fontSize: rf(13),
    color: "#5A189A",
    fontWeight: "500",
  },

  // ─── NOTAS EN TARJETA DE SOLICITUD ────────────────────────────────────────
  notasCardBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    marginHorizontal: 12,
    marginBottom: 8,
    backgroundColor: "#F3EEF8",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderLeftWidth: 3,
    borderLeftColor: "#5A189A",
  },
  notasCardText: {
    fontSize: 12,
    color: "#1a1a1a",
    flex: 1,
    flexWrap: "wrap",
    lineHeight: 17,
  },
  notasCardLabel: {
    fontWeight: "700",
    color: "#5A189A",
  },

  // ─── MODAL FOTO EVIDENCIA ──────────────────────────────────────────────────
  photoModalContainer: {
    flex: 1,
    paddingTop: Platform.OS === "ios" ? 55 : 30,
    paddingHorizontal: 20,
  },
  photoModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  photoModalHeaderTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3B0F5C",
  },
  photoModalSubtitle: {
    fontSize: 13,
    color: "#5A189A",
    marginBottom: 20,
    lineHeight: 18,
  },
  photoImageContainer: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 14,
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  photoImage: {
    width: "100%",
    height: 320,
    borderRadius: 16,
  },
  photoImageBadge: {
    position: "absolute",
    bottom: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  photoImageBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1a1a1a",
  },
  photoOrderInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 20,
  },
  photoOrderInfoText: {
    flex: 1,
    fontSize: 13,
    color: "#3B0F5C",
    fontWeight: "500",
  },
  photoLoadingContainer: {
    alignItems: "center",
    paddingVertical: 30,
    gap: 14,
  },
  photoLoadingText: {
    fontSize: 14,
    color: "#5A189A",
    fontWeight: "500",
    textAlign: "center",
  },
  photoButtonsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  retakeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#5A189A",
    paddingVertical: 14,
    borderRadius: 12,
  },
  retakeButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#5A189A",
  },
  confirmButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#5A189A",
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: "#2A0E3F",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  confirmButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },

  // Aviso foto en pedido aceptado
  photoNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "#F3EEF8",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#5A189A",
  },
  photoNoticeText: {
    flex: 1,
    fontSize: 12,
    color: "#5A189A",
    fontWeight: "500",
  },
})

export default styles