import { Dimensions, Platform, StyleSheet } from "react-native"

const { width } = Dimensions.get("window")

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
 mapContainer: {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  zIndex: 1, // Asegurar que esté por debajo del formulario
},
// En el archivo de estilos, agregar:
mapWithKeyboard: {
  bottom: 0, // Asegurar que el mapa ocupe todo el espacio
},
  map: {
    flex: 1,
  },
  footer: {
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.98)",
    paddingHorizontal: 20,
    paddingTop: 25,
    paddingBottom: Platform.OS === "ios" ? 40 : 30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 15,
    zIndex: 5,
    minHeight: 140,
  },
  footerWithKeyboard: {
    paddingBottom: 15,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    backgroundColor: "rgba(255, 255, 255, 1)",
  },
  collapseButton: {
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 10,
    marginTop: -20,
  },
  formScrollView: {
    flex: 1,
  },
  input: {
    width: "100%",
    height: 50,
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    fontSize: 15,
  },
  inputFocused: {
    borderColor: "#FF1493",
    borderWidth: 2,
    shadowColor: "#FF1493",
    shadowOpacity: 0.3,
    backgroundColor: "#fff",
    elevation: 4,
  },
  inputWithKeyboard: {
    marginBottom: 8,
    shadowOpacity: 0.25,
    elevation: 6,
    backgroundColor: "#fff",
  },
  button: {
    width: "100%",
    backgroundColor: "#FF1493",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 20,
    shadowColor: "#FF1493",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  avatarMenuContainer: {
    position: "absolute",
    top: Platform.OS === "ios" ? 50 : 30,
    right: 20,
    zIndex: 10,
  },
  avatarSmall: {
    width: 50,
    height: 50,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#B33F8D",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 8,
  },
  avatarButtonContainer: {
    shadowColor: "#B33F8D",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  menuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9,
  },
  searchContainer: {
    width: "100%",
    position: "relative",
  },
  vehicleSelectionContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 15,
  },
  vehicleOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  vehicleOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f9f9f9",
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#eee",
  },
  selectedVehicleOption: {
    backgroundColor: "#FF1493",
    borderColor: "#FF1493",
  },
  vehicleText: {
    marginTop: 5,
    fontSize: 14,
    fontWeight: "500",
    color: "#333",
  },
  selectedVehicleText: {
    color: "#fff",
  },
  priceContainer: {
    width: "100%",
    position: "relative",
  },
  priceEstimateText: {
    fontSize: 14,
    color: "#FF1493",
    fontWeight: "600",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 5,
    backgroundColor: "#fff0f5",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ffb6c1",
  },
  buttonDisabled: {
    backgroundColor: "#ffb6c1",
    shadowOpacity: 0.1,
  },
  formOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    zIndex: 4,
  },
})

export default styles
