import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    mapContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    map: {
        flex: 1,
    },
    menuButton: {
        position: "absolute",
        top: Platform.OS === 'ios' ? 50 : 30,
        left: 20,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        padding: 12,
        borderRadius: 50,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        zIndex: 6,
    },
    sidebar: {
        position: "absolute",
        top: 0,
        left: -300, // Hidden initially
        width: 280,
        height: "100%",
        backgroundColor: "#fff",
        paddingTop: Platform.OS === 'ios' ? 50 : 30,
        paddingBottom: 30,
        paddingHorizontal: 20,
        borderRightWidth: 0,
        shadowColor: "#000",
        shadowOffset: { width: 3, height: 0 },
        shadowOpacity: 0.27,
        shadowRadius: 4.65,
        elevation: 8,
        zIndex: 10,
    },
    closeButton: {
        position: "absolute",
        top: Platform.OS === 'ios' ? 50 : 30,
        right: 15,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        padding: 10,
        borderRadius: 50,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 4,
        zIndex: 11,
    },
    mapOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.15)',
        zIndex: 5,
    },
    avatarMenuContainer: {
        position: "absolute",
        top: Platform.OS === "ios" ? 50 : 30,
        right: 20,
        zIndex: 10,
    },
    avatarSmall: {
        width: 50,
        height: 50,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: "#FFE4F3",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 8,
    },
    avatarButtonContainer: {
        shadowColor: "#FFE4F3",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    menuOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9,
    },
    
    // Nuevos estilos para la vista de la conductora
    driverFooter: {
        position: "absolute",
        bottom: 0,
        width: "100%",
        backgroundColor: "#FFE4F3",
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 35 : 25,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 10,
        zIndex: 5,
    },
    footerContent: {
        width: "100%",
        alignItems: "center",
    },
    statusContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        width: "100%",
        marginBottom: 15,
        backgroundColor: "#fff",
        padding: 15,
        borderRadius: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 2,
    },
    statusText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
    },
    statusSwitch: {
        transform: [{ scaleX: 1.1 }, { scaleY: 1.1 }],
    },
    driverLocationText: {
        fontSize: 14,
        color: "#444",
        textAlign: "center",
        marginBottom: 10,
        paddingHorizontal: 20,
    },
    driverStatusInfo: {
        fontSize: 15,
        fontWeight: "500",
        textAlign: "center",
    },
    
    // Estilos para el panel de solicitud de viaje
    rideRequestContainer: {
        position: "absolute",
        bottom: 150, // Posicionado por encima del footer
        left: 20,
        right: 20,
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 8,
        zIndex: 8,
    },
    rideRequestHeader: {
        marginBottom: 12,
    },
    rideRequestTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#333",
    },
    
    // Nuevos estilos para la información del pasajero
    passengerInfoContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
        paddingBottom: 8,
    },
    passengerPhoto: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        marginRight: 12,
        borderWidth: 1.5,
        borderColor: "#FFE4F3",
    },
    passengerDetails: {
        flex: 1,
    },
    passengerName: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        marginBottom: 2,
    },
    contactButtons: {
        flexDirection: "row",
    },
    contactButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#f5f5f5",
        justifyContent: "center",
        alignItems: "center",
        marginLeft: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
    },
    phoneContainer: {
        marginBottom: 10,
    },
    phoneText: {
        fontSize: 14,
        color: "#666",
        marginLeft: 58, // Alineado con el nombre del pasajero
    },
    divider: {
        height: 1,
        backgroundColor: "#f0f0f0",
        marginVertical: 10,
    },
    
    rideRequestDetails: {
        marginVertical: 12,
    },
    locationRow: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 6,
    },
    locationPoint: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#4CAF50",
        marginRight: 10,
    },
    destinationPoint: {
        backgroundColor: "#FF69B4",
    },
    locationText: {
        fontSize: 15,
        color: "#333",
        flex: 1,
    },
    verticalLine: {
        width: 2,
        height: 20,
        backgroundColor: "#ddd",
        marginLeft: 4,
    },
    rideMetrics: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginVertical: 12,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: "#f0f0f0",
    },
    metricItem: {
        flexDirection: "row",
        alignItems: "center",
    },
    metricText: {
        marginLeft: 5,
        fontSize: 15,
        fontWeight: "500",
        color: "#555",
    },
    rideRequestActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 10,
    },
    acceptButton: {
        backgroundColor: "#4CAF50",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        flex: 1,
        marginLeft: 8,
    },
    rejectButton: {
        backgroundColor: "#FF5252",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        flex: 1,
        marginRight: 8,
    },
    actionButtonText: {
        color: "#fff",
        fontWeight: "600",
        fontSize: 15,
        marginLeft: 5,
    },
    
    // Manteniendo estilos originales necesarios
    input: {
        width: "100%",
        height: 50,
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingHorizontal: 15,
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 2,
        borderWidth: 1,
        borderColor: "#f0f0f0",
        fontSize: 15,
    },
    buttonText: {
        color: "#FF69B4",
        fontSize: 16,
        fontWeight: "700",
        letterSpacing: 0.5,
    },
});

export default styles;